package br.com.pesquisafacil.formulario;

import br.com.pesquisafacil.persistencia.ConectarBD;
import br.com.pesquisafacil.modelo.Pergunta;
import br.com.pesquisafacil.modelo.Avaliacao;
import br.com.pesquisafacil.modelo.Cliente;
import br.com.pesquisafacil.persistencia.AvaliacaoDAO;
import br.com.pesquisafacil.persistencia.ClienteDAO;
import java.sql.PreparedStatement;
import java.util.Calendar; 
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author luciano
 */
public class NovaAvaliacao extends javax.swing.JFrame {

  ConectarBD conexao = new ConectarBD();

  /* Em construção */
  Calendar calendario = Calendar.getInstance();
  int dia = calendario.get(Calendar.DAY_OF_MONTH);
  int mes = calendario.get(Calendar.MONTH) + 1;
  int ano = calendario.get(Calendar.YEAR);
  String data = "" + dia + "/" + mes + "/" + ano;

  /* Em construção: Para vetorizar as perguntas do BD e formar as respostas */
  int count = 0;
  int numPerguntas = 6;
  Pergunta[] perguntas = new Pergunta[numPerguntas];
  Avaliacao novaResposta = new Avaliacao(numPerguntas);  
  Cliente novoCliente = new Cliente("test");
  ClienteDAO gravarCliente;
  AvaliacaoDAO gravarAvaliacao;

  /**
   * Creates new form Principal
   */
  public NovaAvaliacao() {
    initComponents();
    apagarEstrelas();
    novaResposta.setData(data);
    definirPerguntas(perguntas);
    mudarPerguntas();
  }

  private void apagarEstrelas() {
    star1.setEnabled(false);
    star2.setEnabled(false);
    star3.setEnabled(false);
    star4.setEnabled(false);
    star5.setEnabled(false);
  }

  private void visibilidadePaineis() {
    if (count <= 2) {
      star1.setVisible(true);
      star2.setVisible(true);
      star3.setVisible(true);
      star4.setVisible(true);
      star5.setVisible(true);
      respondeSim.setVisible(false);
      respondeNao.setVisible(false);
      jTextField.setVisible(false);
    }
    if (count == 3) {
      respondeSim.setVisible(true);
      respondeNao.setVisible(true);
      star1.setVisible(false);
      star2.setVisible(false);
      star3.setVisible(false);
      star4.setVisible(false);
      star5.setVisible(false);
      jTextField.setVisible(false);
    }
    if (count == 4 || count == 5) {
      jTextField.setText("");
      jTextField.setVisible(true);
      respondeSim.setVisible(false);
      respondeNao.setVisible(false);
      star1.setVisible(false);
      star2.setVisible(false);
      star3.setVisible(false);
      star4.setVisible(false);
      star5.setVisible(false);
    }
  }

  private void definirPerguntas(Pergunta[] perguntas) {
    try {
      conexao.openConection();
      for (int i = 0; i < numPerguntas; i++) {
	conexao.executaSQL("select ID_PERGUNTA, pergunta, TEXT_AJUDA from TB_PERGUNTA where ID_PERGUNTA = " + (i + 1) + "");
	conexao.rs.first();
	Pergunta p;
	p = new Pergunta(
		conexao.rs.getInt("ID_PERGUNTA"),
		String.valueOf(conexao.rs.getString("PERGUNTA")),
		String.valueOf(conexao.rs.getString("TEXT_AJUDA"))
	);
	perguntas[i] = p;
      }
      conexao.closeConection();

    } catch (SQLException ex) {
      JOptionPane.showMessageDialog(null, "Erro na definição das perguntas: " + ex);
    }
  }

  private void mudarPerguntas() {
    apagarEstrelas();
    numPerguntas--;
    if (count < 6) {
      jLabelPerguntaId.setText(String.valueOf(perguntas[count].getId()) + ")");
      jLabelPerguntaTitulo.setText(perguntas[count].getEnunciado());
      jLabelPerguntaAjuda.setText(perguntas[count].getTextoAjuda());
      jLabelPerguntaHelper1.setText("Resta(m)");
      jLabelPerguntaNumero.setText(String.valueOf(numPerguntas));
      jLabelPerguntaHelper2.setText("pergunta(s)");
      visibilidadePaineis();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel2 = new javax.swing.JPanel();
    jLabelLogotipo = new javax.swing.JLabel();
    jPanelPergunta = new javax.swing.JPanel();
    jLabelPerguntaTitulo = new javax.swing.JLabel();
    jLabelPerguntaAjuda = new javax.swing.JLabel();
    jLabelPerguntaId = new javax.swing.JLabel();
    jPanelButtons = new javax.swing.JPanel();
    jButtonVoltar = new javax.swing.JButton();
    jButtonProxima = new javax.swing.JButton();
    jLabelPerguntaHelper2 = new javax.swing.JLabel();
    jLabelPerguntaHelper1 = new javax.swing.JLabel();
    jLabelPerguntaNumero = new javax.swing.JLabel();
    jPanelRespostas = new javax.swing.JPanel();
    star1 = new javax.swing.JLabel();
    star2 = new javax.swing.JLabel();
    star3 = new javax.swing.JLabel();
    star4 = new javax.swing.JLabel();
    star5 = new javax.swing.JLabel();
    respondeNao = new javax.swing.JLabel();
    respondeSim = new javax.swing.JLabel();
    jTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Avaliação do Cliente");
    setResizable(false);

    jLabelLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/logo-espaco-fashion-hair-small.png"))); // NOI18N

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(jLabelLogotipo)
        .addContainerGap(26, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jLabelPerguntaTitulo.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
    jLabelPerguntaTitulo.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelPerguntaTitulo.setText("Título da pergunta");

    jLabelPerguntaAjuda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabelPerguntaAjuda.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaAjuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelPerguntaAjuda.setLabelFor(jLabelPerguntaTitulo);
    jLabelPerguntaAjuda.setText("Texto de ajuda da pergunta");
    jLabelPerguntaAjuda.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    jLabelPerguntaId.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
    jLabelPerguntaId.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelPerguntaId.setText("ID");

    javax.swing.GroupLayout jPanelPerguntaLayout = new javax.swing.GroupLayout(jPanelPergunta);
    jPanelPergunta.setLayout(jPanelPerguntaLayout);
    jPanelPerguntaLayout.setHorizontalGroup(
      jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelPerguntaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelPerguntaAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanelPerguntaLayout.createSequentialGroup()
            .addComponent(jLabelPerguntaId)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabelPerguntaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanelPerguntaLayout.setVerticalGroup(
      jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelPerguntaLayout.createSequentialGroup()
        .addGroup(jPanelPerguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelPerguntaTitulo)
          .addComponent(jLabelPerguntaId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelPerguntaAjuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jButtonVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonVoltar.setForeground(new java.awt.Color(102, 102, 102));
    jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-voltar.png"))); // NOI18N
    jButtonVoltar.setText("VOLTAR");
    jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVoltarActionPerformed(evt);
      }
    });

    jButtonProxima.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jButtonProxima.setForeground(new java.awt.Color(102, 102, 102));
    jButtonProxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-next.png"))); // NOI18N
    jButtonProxima.setText("PRÓXIMA");
    jButtonProxima.setBorderPainted(false);
    jButtonProxima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonProxima.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    jButtonProxima.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonProximaActionPerformed(evt);
      }
    });

    jLabelPerguntaHelper2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelPerguntaHelper2.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaHelper2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabelPerguntaHelper2.setText("perguntas");

    jLabelPerguntaHelper1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelPerguntaHelper1.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaHelper1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabelPerguntaHelper1.setText("Restam");

    jLabelPerguntaNumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabelPerguntaNumero.setForeground(new java.awt.Color(153, 153, 153));
    jLabelPerguntaNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabelPerguntaNumero.setText("N");

    javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
    jPanelButtons.setLayout(jPanelButtonsLayout);
    jPanelButtonsLayout.setHorizontalGroup(
      jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelButtonsLayout.createSequentialGroup()
        .addGap(44, 44, 44)
        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
        .addComponent(jLabelPerguntaHelper1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabelPerguntaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabelPerguntaHelper2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(132, 132, 132)
        .addComponent(jButtonProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(41, 41, 41))
    );
    jPanelButtonsLayout.setVerticalGroup(
      jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelButtonsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelPerguntaHelper2)
          .addComponent(jLabelPerguntaHelper1)
          .addComponent(jLabelPerguntaNumero))
        .addContainerGap(25, Short.MAX_VALUE))
    );

    star1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    star1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-estrela.png"))); // NOI18N
    star1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    star1.setEnabled(false);
    star1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        star1MouseClicked(evt);
      }
    });

    star2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    star2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-estrela.png"))); // NOI18N
    star2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    star2.setEnabled(false);
    star2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        star2MouseClicked(evt);
      }
    });

    star3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    star3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-estrela.png"))); // NOI18N
    star3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    star3.setEnabled(false);
    star3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        star3MouseClicked(evt);
      }
    });

    star4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    star4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-estrela.png"))); // NOI18N
    star4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    star4.setEnabled(false);
    star4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        star4MouseClicked(evt);
      }
    });

    star5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    star5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-estrela.png"))); // NOI18N
    star5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    star5.setEnabled(false);
    star5.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        star5MouseClicked(evt);
      }
    });

    respondeNao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    respondeNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-dislike.png"))); // NOI18N
    respondeNao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    respondeNao.setEnabled(false);
    respondeNao.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        respondeNaoMouseClicked(evt);
      }
    });

    respondeSim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    respondeSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pesquisafacil/imagem/icone-like.png"))); // NOI18N
    respondeSim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    respondeSim.setEnabled(false);
    respondeSim.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        respondeSimMouseClicked(evt);
      }
    });

    jTextField.setBackground(new java.awt.Color(250, 250, 250));
    jTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jTextField.setForeground(new java.awt.Color(153, 153, 153));
    jTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextField.setSelectionColor(new java.awt.Color(255, 153, 255));
    jTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanelRespostasLayout = new javax.swing.GroupLayout(jPanelRespostas);
    jPanelRespostas.setLayout(jPanelRespostasLayout);
    jPanelRespostasLayout.setHorizontalGroup(
      jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelRespostasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(star1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(34, 34, 34)
        .addComponent(star2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(31, 31, 31)
        .addComponent(star3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(33, 33, 33)
        .addComponent(star4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        .addGap(31, 31, 31)
        .addComponent(star5, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelRespostasLayout.createSequentialGroup()
          .addGap(307, 307, 307)
          .addComponent(respondeNao, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
          .addGap(34, 34, 34)
          .addComponent(respondeSim, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
          .addGap(307, 307, 307)))
      .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelRespostasLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(jTextField)
          .addContainerGap()))
    );
    jPanelRespostasLayout.setVerticalGroup(
      jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelRespostasLayout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(star5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(star4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(23, Short.MAX_VALUE))
      .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelRespostasLayout.createSequentialGroup()
          .addGap(22, 22, 22)
          .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(respondeSim, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(respondeNao, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addContainerGap(22, Short.MAX_VALUE)))
      .addGroup(jPanelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanelRespostasLayout.createSequentialGroup()
          .addGap(19, 19, 19)
          .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(22, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanelButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanelRespostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanelPergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(384, 384, 384)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(13, 13, 13)
        .addComponent(jPanelRespostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void star1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseClicked
    // TODO add your handling code here:
    novaResposta.setNota(count, 1);
    if (star1.isEnabled() && star2.isEnabled()) {
      star5.setEnabled(false);
      star2.setEnabled(false);
      star3.setEnabled(false);
      star4.setEnabled(false);
    } else if (star1.isEnabled()) {
      //star1.setEnabled(false);
    } else {
      star1.setEnabled(true);

    }
  }//GEN-LAST:event_star1MouseClicked

  private void star2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseClicked
    // TODO add your handling code here    
    novaResposta.setNota(count, 2);
    if (star2.isEnabled() && star3.isEnabled()) {
      star5.setEnabled(false);
      star4.setEnabled(false);
      star3.setEnabled(false);
    } else if (star2.isEnabled()) {
      star4.setEnabled(false);
    } else {
      star1.setEnabled(true);
      star2.setEnabled(true);

    }
  }//GEN-LAST:event_star2MouseClicked

  private void star3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseClicked
    // TODO add your handling code here:    
    novaResposta.setNota(count, 3);
    if (star3.isEnabled() && star4.isEnabled()) {
      star5.setEnabled(false);
      star4.setEnabled(false);
    } else if (star3.isEnabled()) {
      star3.setEnabled(false);
    } else {
      star1.setEnabled(true);
      star2.setEnabled(true);
      star3.setEnabled(true);
    }
  }//GEN-LAST:event_star3MouseClicked

  private void star4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseClicked
    // TODO add your handling code here:    
    novaResposta.setNota(count, 4);
    if (star4.isEnabled() && star5.isEnabled()) {
      star5.setEnabled(false);
    } else if (star4.isEnabled()) {
      star4.setEnabled(false);
    } else {
      star4.setEnabled(true);
      star1.setEnabled(true);
      star2.setEnabled(true);
      star3.setEnabled(true);
    }
  }//GEN-LAST:event_star4MouseClicked

  private void star5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseClicked
    // TODO add your handling code here:    
    novaResposta.setNota(count, 5);
    if (star5.isEnabled()) {
      star5.setEnabled(false);
    } else {
      star5.setEnabled(true);
      star1.setEnabled(true);
      star2.setEnabled(true);
      star3.setEnabled(true);
      star4.setEnabled(true);
    }
  }//GEN-LAST:event_star5MouseClicked

  private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    if (count == 0) {
      Principal voltou = new Principal();
      voltou.setVisible(true);
      this.setVisible(false);
    } else {
      count--;
      numPerguntas += 2;
      mudarPerguntas();
    }
    visibilidadePaineis();
  }//GEN-LAST:event_jButtonVoltarActionPerformed

  private void jButtonProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximaActionPerformed
    if (count < 7) {
      if (count == 4) {
	novoCliente.setEmail(jTextField.getText());
      }
      if (count == 5) {
	novaResposta.setComentario(jTextField.getText());
      }
      count++;
      mudarPerguntas();
    }
    if (count == 6) {
      agradecimento();
      gravarCliente = new ClienteDAO(novoCliente);
      gravarAvaliacao = new AvaliacaoDAO(novaResposta);
    }
    System.out.println("Pergunta ".toUpperCase() + count);
  }//GEN-LAST:event_jButtonProximaActionPerformed

  private void respondeNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respondeNaoMouseClicked
    novaResposta.setSimNao(false);
    respondeNao.setEnabled(true);
    respondeSim.setEnabled(false);
  }//GEN-LAST:event_respondeNaoMouseClicked

  private void respondeSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respondeSimMouseClicked
    novaResposta.setSimNao(true);
    respondeSim.setEnabled(true);
    respondeNao.setEnabled(false);
  }//GEN-LAST:event_respondeSimMouseClicked

  private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed

  }//GEN-LAST:event_jTextFieldActionPerformed

  private void agradecimento() {
    Agradecimento valeu = new Agradecimento();
    this.setVisible(false);
    valeu.setVisible(true);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	if ("Nimbus".equals(info.getName())) {
	  javax.swing.UIManager.setLookAndFeel(info.getClassName());
	  break;
	}
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(NovaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(NovaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(NovaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(NovaAvaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
	new NovaAvaliacao().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonProxima;
  private javax.swing.JButton jButtonVoltar;
  private javax.swing.JLabel jLabelLogotipo;
  private javax.swing.JLabel jLabelPerguntaAjuda;
  private javax.swing.JLabel jLabelPerguntaHelper1;
  private javax.swing.JLabel jLabelPerguntaHelper2;
  private javax.swing.JLabel jLabelPerguntaId;
  private javax.swing.JLabel jLabelPerguntaNumero;
  private javax.swing.JLabel jLabelPerguntaTitulo;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanelButtons;
  private javax.swing.JPanel jPanelPergunta;
  private javax.swing.JPanel jPanelRespostas;
  private javax.swing.JTextField jTextField;
  private javax.swing.JLabel respondeNao;
  private javax.swing.JLabel respondeSim;
  private javax.swing.JLabel star1;
  private javax.swing.JLabel star2;
  private javax.swing.JLabel star3;
  private javax.swing.JLabel star4;
  private javax.swing.JLabel star5;
  // End of variables declaration//GEN-END:variables
}
